title: Il Catalogo BIFLOW - Toscana bilingue
baseurl: ""
preloadurl: "https://mizar.unive.it/catalogo_biflow/preload.js"
url: "http://catalogobiflow.vedph.it"
emails: [antonio.montefusco@unive.it, sara.bischetti@unive.it, tiziana.mancinelli@unive.it]

# Build settings
markdown: kramdown
