name: Gen
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  gen:
    name: Gen DB
    runs-on: ubuntu-22.04
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run
        shell: bash
        run: node tools/fetcher.js > js/preload.js

      - name: Commit
        run: |
          git config --global user.name "Tiziana Mancinelli"
          git config --global user.email "tiziana.mancinelli@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add js/preload.js
          git commit -m "Stats updated" && git push || echo "Nothing to commit"
